---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  annotations:
    tekton.dev/pipelines.minVersion: 0.12.1
    tekton.dev/tags: git  
  name: update-gitops
  labels:
    app.kubernetes.io/version: '0.1'
    operator.tekton.dev/provider-type: community
spec:
  description: This Task can be used to update image tag in a Git repo
  params:
    - name: GIT_MANIFESTS_PROTOCOL
      type: string
    - name: GIT_MANIFESTS_HOST
      type: string
    - name: GIT_MANIFESTS
      type: string
    - name: GIT_MANIFESTS_BRANCH     
      type: string
    - name: HELM_PATH
      type: string
    - name: TAG
      type: string
    - name: git-secret-name
      type: string
  results:
    - description: The commit SHA
      name: commit
  steps:      
    - image: 'docker.io/alpine/git:v2.26.2'
      name: git-clone
      env:
        - name: GIT_TOKEN
          valueFrom:
            secretKeyRef:
              key: password
              name: $(params.git-secret-name)
        - name: GIT_USER
          valueFrom:
            secretKeyRef:
              key: username
              name: $(params.git-secret-name)
      resources: {}
      script: |
        rm -fr git-update-tag-workdir

        echo "Git user: $GIT_USER"

        git config --global user.email "tekton@pipeline.com"
        git config --global user.name "$GIT_USER"
        git config --global http.sslVerify false

        git clone -b $(params.GIT_MANIFESTS_BRANCH) $(params.GIT_MANIFESTS_PROTOCOL)://$GIT_USER:$GIT_TOKEN@$(params.GIT_MANIFESTS_HOST)/$(params.GIT_MANIFESTS).git git-update-tag-workdir

        cd git-update-tag-workdir 
        cd $(params.HELM_PATH)

        echo "looking for nameVersion: field in files"
        VALUE_FILE=$(grep "nameVersion:" * |awk -F":" '{print $1}')
        LAST_IMAGE=$(grep "nameVersion:" $VALUE_FILE |awk -F":" '{print $4}')
        echo "Helm Value File found: $VALUE_FILE"
        echo "Current Image Version: $LAST_IMAGE"
        echo "New Image Version: $(params.TAG)"
        LI=$(echo -n $LAST_IMAGE)

        sed -i "s/$LI/$(params.TAG)/g" $VALUE_FILE

        git status

        echo "Executing git add"
        git add .      

        echo "Executing git commit "        
        git commit -m "[$(context.taskRun.name)] Image tag updated"             

        echo "Executing git push"
        git push
      workingDir: $(workspaces.workspace.path)
      
  workspaces:
    - description: The workspace consisting of maven project.
      name: workspace
